version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sumo-node-app
    container_name: app
    ports:
      - "8000:8000"
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 20s docker-entrypoint.sh
    command: ["npm","run","start"]
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - /usr/src/app/node_modules  # Keep node_modules in the container
    depends_on:
      - redis
    networks:
      - sumo-network

  redis:
    image: "redis:latest"
    container_name: sumo-redis
    ports:
      - "6379:6379"
    networks:
      - sumo-network

networks:
  sumo-network:
    driver: bridge